name = "aerovanta-api"
main = "src/index.js"
compatibility_date = "2026-03-05"

[vars]
API_PREFIX = "/api/v1"
CORS_ORIGINS = "http://localhost:5173,https://aerovanta-web.pages.dev,https://*.aerovanta-web.pages.dev"
FORCE_HTTPS = "true"
ALLOW_SOCIAL_PROFILE_ONLY = "true"
GOOGLE_CLIENT_ID = "9617483363-a541g6qkanohf54qr1h7lnofqouvb7n6.apps.googleusercontent.com"
ENTRA_CLIENT_ID = "e62907f0-d4a3-4a4c-a053-5012ae0e2aa2"
ENTRA_TENANT_ID = "common"
FACEBOOK_APP_ID = "1780336486260915"
EXPOSE_RESET_DEBUG_URL = "true"
APP_BASE_URL = "https://aerovanta-web.pages.dev"
APP_NAME = "Aerovanta"
EMAIL_PROVIDER = "resend"
RESET_EMAIL_FROM = "security@aerovanta.com"
RESET_EMAIL_REPLY_TO = ""
ADMIN_EMAIL = "admin@aerovanta.com"
SESSION_COOKIE_NAME = "vv_session"
CSRF_COOKIE_NAME = "vv_csrf"
SESSION_COOKIE_SAMESITE = "None"
PASSWORD_ITERATIONS = "100000"
PASSWORD_MIN_LENGTH = "12"
DEFAULT_SESSION_HOURS = "8"
REMEMBER_SESSION_DAYS = "30"

[[d1_databases]]
binding = "DB"
database_name = "aerovanta"
database_id = "b431d1c0-f59e-4e0c-91e8-2f2166ad5aa0"










